### ISSUE TITLE
add Fatal log level

### ISSUE THREAD

**Issue by milhamsuryapratama** [milhamsuryapratama/bulog#1]

**Comment by salman0ansari** [comment]
@milhamsuryapratama Can you assign this to me?

**Comment by milhamsuryapratama** [comment]
yes, sure. thank you for your contribution @salman0ansari

**Comment by salman0ansari** [comment]
@milhamsuryapratama add `hacktoberfest-accepted` label to both PRs I made
![image](https://user-images.githubusercontent.com/30106022/194711040-d14c5a4f-457a-4652-986d-7e7c72a62fe8.png)

**Comment by salman0ansari** [comment]
> @milhamsuryapratama add `hacktoberfest-accepted` label to both PRs i made
![image](https://user-images.githubusercontent.com/30106022/194711031-cb9efb38-ed3a-4f2f-92f6-fa680e97eaaf.png)
